language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - cp src/containers/ApiKey.js.sample src/containers/ApiKey.js
  - yarn build
  - yarn lint
  - yarn test
